export const rightTetrisData = [
    {
        id: 1,
        content: "",
        color: "transparent",
    },
    { id: 2, content: "", color: "transparent" },
    { id: 3, content: "", color: "transparent" },
    { id: 4, content: "", color: "black" },
    {
        id: 5,
        content: "",
        color: "transparent",
    },
    { id: 6, content: "", color: "brand.yellow" },
    {
        id: 7,
        content: "",
        color: "transparent",
    },
    { id: 8, content: "", color: "transparent" },
    { id: 9, content: "", color: "black" },
    {
        id: 10,
        content: "",
        color: "transparent",
    },
    { id: 11, content: "", color: "transparent" },

    { id: 12, content: "", color: "brand.yellow" },
    { id: 13, content: "", color: "transparent" },
    {
        id: 14,
        content: "",
        color: "transparent",
    },
    { id: 15, content: "", color: "transparent" },
    {
        id: 16,
        content: "",
        color: "brand.orange.main",
    },
    { id: 17, content: "", color: "transparent" },
    { id: 18, content: "", color: "transparent" },
    {
        id: 19,
        content: "",
        color: "transparent",
    },
    { id: 20, content: "", color: "transparent" },
    { id: 21, content: "", color: "transparent" },
    { id: 22, content: "", color: "brand.yellow" },

    {
        id: 23,
        content: "",
        color: "transparent",
    },
    { id: 24, content: "", color: "transparent" },
    {
        id: 25,
        content: "",
        color: "transparent",
    },
    { id: 26, content: "", color: "transparent" },
    { id: 27, content: "", color: "transparent" },
    {
        id: 28,
        content: "",
        color: "transparent",
    },
    { id: 29, content: "", color: "transparent" },
    { id: 30, content: "", color: "brand.orange.main" },
    { id: 31, content: "", color: "transparent" },
    {
        id: 32,
        content: "",
        color: "transparent",
    },
    { id: 33, content: "", color: "transparent" },

    {
        id: 34,
        content: "",
        color: "transparent",
    },
    { id: 35, content: "", color: "transparent" },
    { id: 36, content: "", color: "black" },
    { id: 37, content: "", color: "transparent" },
    { id: 38, content: "", color: "transparent" },
    { id: 39, content: "", color: "transparent" },
    { id: 40, content: "", color: "transparent" },
    { id: 41, content: "", color: "transparent" },
    { id: 42, content: "", color: "transparent" },
    { id: 43, content: "", color: "transparent" },
    { id: 44, content: "", color: "transparent" },
];

export const leftTetrisData = [
    {
        id: 1,
        content: "",
        color: "transparent",
    },
    { id: 2, content: "", color: "transparent" },
    { id: 3, content: "", color: "transparent" },
    { id: 4, content: "", color: "transparent" },
    {
        id: 5,
        content: "",
        color: "transparent",
    },
    { id: 6, content: "", color: "transparent" },
    {
        id: 7,
        content: "",
        color: "transparent",
    },
    { id: 8, content: "", color: "transparent" },
    { id: 9, content: "", color: "brand.orange.main" },
    {
        id: 10,
        content: "",
        color: "transparent",
    },
    { id: 11, content: "", color: "transparent" },

    { id: 12, content: "", color: "transparent" },
    { id: 13, content: "", color: "transparent" },
    {
        id: 14,
        content: "",
        color: "transparent",
    },
    { id: 15, content: "", color: "black" },
    {
        id: 16,
        content: "",
        color: "transparent",
    },
    { id: 17, content: "", color: "transparent" },
    { id: 18, content: "", color: "transparent" },
    {
        id: 19,
        content: "",
        color: "transparent",
    },
    { id: 20, content: "", color: "transparent" },
    { id: 21, content: "", color: "transparent" },
    { id: 22, content: "", color: "transparent" },

    {
        id: 23,
        content: "",
        color: "transparent",
    },
    { id: 24, content: "", color: "transparent" },
    {
        id: 25,
        content: "",
        color: "brand.yellow",
    },
    { id: 26, content: "", color: "transparent" },
    { id: 27, content: "", color: "transparent" },
    {
        id: 28,
        content: "",
        color: "transparent",
    },
    { id: 29, content: "", color: "transparent" },
    { id: 30, content: "", color: "brand.orange.main" },
    { id: 31, content: "", color: "transparent" },
    {
        id: 32,
        content: "",
        color: "transparent",
    },
    { id: 33, content: "", color: "black" },

    {
        id: 34,
        content: "",
        color: "brand.orange.main",
    },
    { id: 35, content: "", color: "transparent" },
    { id: 36, content: "", color: "transparent" },
    { id: 37, content: "", color: "transparent" },
    { id: 38, content: "", color: "transparent" },
    { id: 39, content: "", color: "black" },
    { id: 40, content: "", color: "transparent" },
    { id: 41, content: "", color: "transparent" },
    { id: 42, content: "", color: "brand.yellow" },
    { id: 43, content: "", color: "transparent" },
    { id: 44, content: "", color: "transparent" },
];

export const topTetrisData = [
    {
        id: 1,
        content: "",
        color: "brand.orange.main",
    },
    { id: 2, content: "", color: "transparent" },
    { id: 3, content: "", color: "transparent" },
    { id: 4, content: "", color: "transparent" },
    {
        id: 5,
        content: "",
        color: "transparent",
    },
    { id: 6, content: "", color: "transparent" },
    {
        id: 7,
        content: "",
        color: "transparent",
    },
    { id: 8, content: "", color: "brand.yellow" },
    { id: 9, content: "", color: "transparent" },
    {
        id: 10,
        content: "",
        color: "transparent",
    },
    { id: 11, content: "", color: "transparent" },

    { id: 12, content: "", color: "black" },
    { id: 13, content: "", color: "transparent" },
    {
        id: 14,
        content: "",
        color: "transparent",
    },
    { id: 15, content: "", color: "transparent" },
    {
        id: 16,
        content: "",
        color: "transparent",
    },
    { id: 17, content: "", color: "transparent" },
    { id: 18, content: "", color: "brand.yellow" },
    {
        id: 19,
        content: "",
        color: "black",
    },
    { id: 20, content: "", color: "transparent" },
    { id: 21, content: "", color: "transparent" },
    { id: 22, content: "", color: "transparent" },

    {
        id: 23,
        content: "",
        color: "brand.orange.main",
    },
    { id: 24, content: "", color: "transparent" },
    {
        id: 25,
        content: "",
        color: "brand.yellow",
    },
    { id: 26, content: "", color: "transparent" },
    { id: 27, content: "", color: "transparent" },
    {
        id: 28,
        content: "",
        color: "transparent",
    },
    { id: 29, content: "", color: "transparent" },
    { id: 30, content: "", color: "transparent" },
    { id: 31, content: "", color: "transparent" },
    {
        id: 32,
        content: "",
        color: "black",
    },
    { id: 33, content: "", color: "transparent" },
];
