import { HelpingPeopleType } from "../../constants";
import { IPeopleType } from "./types";

export const peopleData: IPeopleType[] = [
    {
        id: 1,
        name: "Jana Doe",
        position: "FE developer",
        image: "/images/people/eliska-story.png",
        type: HelpingPeopleType.GRADUATE,
        text: "Baví mě dolor sit amet, consectetur adipiscing elit. Tortor, consectetur in eu vestibulum dolor sit amet...",
        linkedin: "",
        email: "test@gmail.com",
    },
    {
        id: 2,
        name: "Jana Doe",
        position: "FE developer",
        image: "/images/people/eliska-story.png",
        type: HelpingPeopleType.GRADUATE,
        text: "Baví mě dolor sit amet, consectetur adipiscing elit. Tortor, consectetur in eu vestibulum dolor sit amet...",
        linkedin: "",
        email: "test@gmail.com",
    },
    {
        id: 3,
        name: "Jana Doe",
        position: "FE developer",
        image: "/images/people/eliska-story.png",
        type: HelpingPeopleType.ORGANIZER,
        text: "Baví mě dolor sit amet, consectetur adipiscing elit. Tortor, consectetur in eu vestibulum dolor sit amet...",
        linkedin: "",
        email: "test@gmail.com",
    },
    {
        id: 4,
        name: "Jana Doe",
        position: "FE developer",
        image: "/images/people/eliska-story.png",
        type: HelpingPeopleType.PARTNER,
        text: "Baví mě dolor sit amet, consectetur adipiscing elit. Tortor, consectetur in eu vestibulum dolor sit amet...",
        linkedin: "",
        email: "test@gmail.com",
    },
    {
        id: 5,
        name: "Jana Doe",
        position: "FE developer",
        image: "/images/people/eliska-story.png",
        type: HelpingPeopleType.GRADUATE,
        text: "Baví mě dolor sit amet, consectetur adipiscing elit. Tortor, consectetur in eu vestibulum dolor sit amet...",
        linkedin: "",
        email: "test@gmail.com",
    },
    {
        id: 6,
        name: "Jana Doe",
        position: "FE developer",
        image: "/images/people/eliska-story.png",
        type: HelpingPeopleType.PARTNER,
        text: "Baví mě dolor sit amet, consectetur adipiscing elit. Tortor, consectetur in eu vestibulum dolor sit amet...",
        linkedin: "",
        email: "test@gmail.com",
    },
    {
        id: 7,
        name: "Jana Doe",
        position: "FE developer",
        image: "/images/people/eliska-story.png",
        type: HelpingPeopleType.GRADUATE,
        text: "Baví mě dolor sit amet, consectetur adipiscing elit. Tortor, consectetur in eu vestibulum dolor sit amet...",
        linkedin: "",
        email: "test@gmail.com",
    },
    {
        id: 8,
        name: "Jana Doe",
        position: "FE developer",
        image: "/images/people/eliska-story.png",
        type: HelpingPeopleType.LECTOR,
        text: "Baví mě dolor sit amet, consectetur adipiscing elit. Tortor, consectetur in eu vestibulum dolor sit amet...",
        linkedin: "",
        email: "test@gmail.com",
    },
    {
        id: 9,
        name: "Jana Doe",
        position: "FE developer",
        image: "/images/people/eliska-story.png",
        type: HelpingPeopleType.LECTOR,
        text: "Baví mě dolor sit amet, consectetur adipiscing elit. Tortor, consectetur in eu vestibulum dolor sit amet...",
        linkedin: "",
        email: "test@gmail.com",
    },
    {
        id: 10,
        name: "Jana Doe",
        position: "FE developer",
        image: "/images/people/eliska-story.png",
        type: HelpingPeopleType.LECTOR,
        text: "Baví mě dolor sit amet, consectetur adipiscing elit. Tortor, consectetur in eu vestibulum dolor sit amet...",
        linkedin: "",
        email: "test@gmail.com",
    },
    {
        id: 11,
        name: "Jana Doe",
        position: "FE developer",
        image: "/images/people/eliska-story.png",
        type: HelpingPeopleType.LECTOR,
        text: "Baví mě dolor sit amet, consectetur adipiscing elit. Tortor, consectetur in eu vestibulum dolor sit amet...",
        linkedin: "",
        email: "test@gmail.com",
    },
    {
        id: 12,
        name: "Jana Doe",
        position: "FE developer",
        image: "/images/people/eliska-story.png",
        type: HelpingPeopleType.LECTOR,
        text: "Baví mě dolor sit amet, consectetur adipiscing elit. Tortor, consectetur in eu vestibulum dolor sit amet...",
        linkedin: "",
        email: "test@gmail.com",
    },
    {
        id: 13,
        name: "Jana Doe",
        position: "FE developer",
        image: "/images/people/eliska-story.png",
        type: HelpingPeopleType.LECTOR,
        text: "Baví mě dolor sit amet, consectetur adipiscing elit. Tortor, consectetur in eu vestibulum dolor sit amet...",
        linkedin: "",
        email: "test@gmail.com",
    },
    {
        id: 14,
        name: "Jana Doe",
        position: "FE developer",
        image: "/images/people/eliska-story.png",
        type: HelpingPeopleType.LECTOR,
        text: "Baví mě dolor sit amet, consectetur adipiscing elit. Tortor, consectetur in eu vestibulum dolor sit amet...",
        linkedin: "",
        email: "test@gmail.com",
    },
    {
        id: 15,
        name: "Jana Doe",
        position: "FE developer",
        image: "/images/people/eliska-story.png",
        type: HelpingPeopleType.LECTOR,
        text: "Baví mě dolor sit amet, consectetur adipiscing elit. Tortor, consectetur in eu vestibulum dolor sit amet...",
        linkedin: "",
        email: "test@gmail.com",
    },
    {
        id: 16,
        name: "Jana Doe",
        position: "FE developer",
        image: "/images/people/eliska-story.png",
        type: HelpingPeopleType.LECTOR,
        text: "Baví mě dolor sit amet, consectetur adipiscing elit. Tortor, consectetur in eu vestibulum dolor sit amet...",
        linkedin: "",
        email: "test@gmail.com",
    },
    {
        id: 17,
        name: "Jana Doe",
        position: "FE developer",
        image: "/images/people/eliska-story.png",
        type: HelpingPeopleType.PARTNER,
        text: "Baví mě dolor sit amet, consectetur adipiscing elit. Tortor, consectetur in eu vestibulum dolor sit amet...",
        linkedin: "",
        email: "test@gmail.com",
    },
    {
        id: 18,
        name: "Jana Doe",
        position: "FE developer",
        image: "/images/people/eliska-story.png",
        type: HelpingPeopleType.PARTNER,
        text: "Baví mě dolor sit amet, consectetur adipiscing elit. Tortor, consectetur in eu vestibulum dolor sit amet...",
        linkedin: "",
        email: "test@gmail.com",
    },
    {
        id: 19,
        name: "Jana Doe",
        position: "FE developer",
        image: "/images/people/eliska-story.png",
        type: HelpingPeopleType.PARTNER,
        text: "Baví mě dolor sit amet, consectetur adipiscing elit. Tortor, consectetur in eu vestibulum dolor sit amet...",
        linkedin: "",
        email: "test@gmail.com",
    },
    {
        id: 20,
        name: "Jana Doe",
        position: "FE developer",
        image: "/images/people/eliska-story.png",
        type: HelpingPeopleType.PARTNER,
        text: "Baví mě dolor sit amet, consectetur adipiscing elit. Tortor, consectetur in eu vestibulum dolor sit amet...",
        linkedin: "",
        email: "test@gmail.com",
    },
    {
        id: 21,
        name: "Jana Doe",
        position: "FE developer",
        image: "/images/people/eliska-story.png",
        type: HelpingPeopleType.PARTNER,
        text: "Baví mě dolor sit amet, consectetur adipiscing elit. Tortor, consectetur in eu vestibulum dolor sit amet...",
        linkedin: "",
        email: "test@gmail.com",
    },
    {
        id: 22,
        name: "Jana Doe",
        position: "FE developer",
        image: "/images/people/eliska-story.png",
        type: HelpingPeopleType.PARTNER,
        text: "Baví mě dolor sit amet, consectetur adipiscing elit. Tortor, consectetur in eu vestibulum dolor sit amet...",
        linkedin: "",
        email: "test@gmail.com",
    },
    {
        id: 23,
        name: "Jana Doe",
        position: "FE developer",
        image: "/images/people/eliska-story.png",
        type: HelpingPeopleType.PARTNER,
        text: "Baví mě dolor sit amet, consectetur adipiscing elit. Tortor, consectetur in eu vestibulum dolor sit amet...",
        linkedin: "",
        email: "test@gmail.com",
    },
    {
        id: 24,
        name: "Jana Doe",
        position: "FE developer",
        image: "/images/people/eliska-story.png",
        type: HelpingPeopleType.PARTNER,
        text: "Baví mě dolor sit amet, consectetur adipiscing elit. Tortor, consectetur in eu vestibulum dolor sit amet...",
        linkedin: "",
        email: "test@gmail.com",
    },
    {
        id: 25,
        name: "Jana Doe",
        position: "FE developer",
        image: "/images/people/eliska-story.png",
        type: HelpingPeopleType.PARTNER,
        text: "Baví mě dolor sit amet, consectetur adipiscing elit. Tortor, consectetur in eu vestibulum dolor sit amet...",
        linkedin: "",
        email: "test@gmail.com",
    },
    {
        id: 26,
        name: "Jana Doe",
        position: "FE developer",
        image: "/images/people/eliska-story.png",
        type: HelpingPeopleType.GRADUATE,
        text: "Baví mě dolor sit amet, consectetur adipiscing elit. Tortor, consectetur in eu vestibulum dolor sit amet...",
        linkedin: "",
        email: "test@gmail.com",
    },
    {
        id: 27,
        name: "Jana Doe",
        position: "FE developer",
        image: "/images/people/eliska-story.png",
        type: HelpingPeopleType.LECTOR,
        text: "Baví mě dolor sit amet, consectetur adipiscing elit. Tortor, consectetur in eu vestibulum dolor sit amet...",
        linkedin: "",
        email: "test@gmail.com",
    },
    {
        id: 28,
        name: "Jana Doe",
        position: "FE developer",
        image: "/images/people/eliska-story.png",
        type: HelpingPeopleType.PARTNER,
        text: "Baví mě dolor sit amet, consectetur adipiscing elit. Tortor, consectetur in eu vestibulum dolor sit amet...",
        linkedin: "",
        email: "test@gmail.com",
    },
];
